export const CATEGORIS_ACTION_TYPES = {
  SET_CATEGORIS: 'category/SET_CATEGORIES',
  FETCH_CATEGORISE_START: 'categories/FETCH_CATEGORISE_START',
  FETCH_CATEGORISE_SUCCESS: 'categories/FETCH_CATEGORISE_SUCCESS',
  FETCH_CATEGORISE_FAILED: 'categories/FETCH_CATEGORISE_FAILED',
};